### ISSUE TITLE
[Feature Request] Possibility for Local / Remote Scope

### ISSUE THREAD

**Issue by norsemanGrey** [benphelps/homepage#1136]
### Description

This is a really awesome dashboard for my self-hosted services. Great work!

One thing I am missing, which would be great if you could have a look at, is the possibility to have a local and remote scope (if that is the correct terminology).

I have a lot of services which are only accessible locally on my LAN using a local address space. However, some services are also available externally via reverse proxy on a FQDN address. Would it be possible do define both local and external addresses for a service / widget and then show/hide the tiles based on where homepage is accessed from? So if I access homepage internally (e.g. using `http://homepage.at.home` ) only tiles with a local address/url (or both local and external) are shown, and if accessing homepage from the outside (e.g. using `https://homepage.external-domain.com`) only tiles with  an external address/url (or both local and external) are shown.

**Comment by jramsgz** [comment]
I am also interested in this feature. In addition to what @norsemanGrey said, we should consider hiding or preventing access to system information such as CPU, RAM, and Docker stats since exposing that information to the internet could pose a security risk. The switch between LAN and WAN could be detected by checking if the IP accessing the service is within the user-defined LAN address space or not. If connected through a trusted reverse proxy, the homepage should look for the real client IP in the headers.
