### ISSUE TITLE
Omada Widget API issue[Bug] 

### ISSUE THREAD

**Issue by spezzuti** [benphelps/homepage#1562]
### Description

Currently attempting to add Omada widget. API address works as expected in browser, verified login credentials, etc. However, when setting up widget, getting API error:

API Error: Unexpected token 'I', "Internal S"... is not valid JSON

Unsure what is causing this

### Steps to reproduce

1. Add Omada widget info to services
2. save & refresh 
3. API error
![image](https://github.com/benphelps/homepage/assets/71993933/a28f896c-8ca9-4a37-a06a-ae7105e69d28)
![image](https://github.com/benphelps/homepage/assets/71993933/2c68b016-ba41-4001-9920-5b46df621bd1)

### homepage version

v0.6.20 6046f79

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please complete the issue template with all steps including the troubleshooting steps etc

From the template:

> If this is a service widget issue and you do not include any information here your issue will be closed.

**Comment by spezzuti** [comment]
troubleshooting steps (best I was able to attempt)

1. tried url as http://omada.tplinkcloud.com https://omada.tplinkcould.com (also without http or https)
2. tried url as ip:port with http, https and without 
3. checked API URL - this gets response from Omada API {"errorCode":0,"msg":"Success.","result":{"controllerVer":"5.9.31","apiVer":"3","configured":true,"type":1,"supportApp":true,"omadacId":"2064891c44d3bc213e95bfb9769d8473","registeredRoot":true}}
4. verified login credentials are working as expected
5. attempted with and without site:

**Comment by shamoon** [comment]
Thanks. Importantly: did you run those queries from inside the homepage container?

**Comment by shamoon** [comment]
I dont have an Omada device to test with, the logic should be:

`${url}/api/info // I think this is what you posted above`

POST with credentials to `${url}/${cId}/api/v2/login`

that would return a token and finally this is sent to
POST `${url}/${cId}/api/v2/sites?token=${token}&currentPage=1&currentPageSize=1000`
substituting in the token and passing it also in the headers ie `"Csrf-Token": token`

I realize this is not trivial to construct the cURL requests but I am not aware of any issues with the widget and the vast majority of the time issues like this are somewhere in your setup i.e. networking, authentication etc. and not a bug here. The only real way to know is to re-create the logic of the widget and see if / where things go wrong. If you can provide API output (again, from inside the homepage container) for the above and they all look normal then I can try to see if theres a real bug here.

**Comment by spezzuti** [comment]
so, ignore any ignorance of mine, but I'm still  not perfect with docker yet. Generally, doing anything from within the container, I use the console on Portainer, which I can't do with Homepage (as it doesn't allow me use of the console)

I have run the curl commands from the server running the container:
 curl <ip:port>/cID/api/v2/login = curl: (35) error:0A00010B:SSL routines::wrong version number

checking the URL via browser returns: {"errorCode":-1600,"msg":"Unsupported request path."}

So either way I'm not receiving any token. Granted, I may be missing something in between at the moment. You let me know what else I can do and I'm ready. Also, thank you in advance
