### ISSUE TITLE
Jellyseerr widget

### ISSUE THREAD

**Issue by ilusi0n** [benphelps/homepage#39]
Hello @benphelps !
I implemented the jellyseerr widget in https://github.com/benphelps/homepage/pull/34 but I guess I messed up something. The widgets works indeed when using the pnpm. But when using the dockerized app it doesn't work since the request is returning a 500 internal server error.
I already tried to google it but no avail. Do you have any tips or ideas what could be the cause and how to solve it?

Thanks!

**Comment by Trever123** [comment]
When using docker are you using it in bridge mode or host mode? I ask because the IP you are using may be wrong for jellyseerr depending on your docker setup. (If bridge mode, you’ll need jellyseerr to also be in docker and to use the internal docker ip/container name, not the actual IP of the host)

**Comment by ilusi0n** [comment]
I'm using on a bridge mode. I created my network and all my containers are on that network. The other widgets work just fine. I have all my containers behind a reverse proxy and they don't need the docker ip/container name to access them.
With jellyseerr doesnt work. But, if I use the internal docker ip/container name as you suggested it works quite fine. Must be something related with the proxy api I think.
Gonna close this since it's not a big deal at least for me!
