### ISSUE TITLE
[Bug] Layout settings not picked up after update

### ISSUE THREAD

**Issue by BitWuehler** [benphelps/homepage#576]
### Description

Seems like homepage is not using my settings.yaml after the last update with the fix for an emtpy settings.yaml. My is not empty!

### Steps to reproduce

Just start it and every setting I made is not applied.

### homepage version

v0.5.2

### Installation method

Docker

### Configuration

```yaml
Raspberry Pi 4
```

### Container Logs

just:
Listening on port 3000

**Comment by Magelo** [comment]
Hi, my settings.yaml is used on v0.5.2, have you tried to hit the refresh/recreate lower right rounded arrow?
![image](https://user-images.githubusercontent.com/10362303/204541255-52c8a48d-059f-4187-b31f-2de7464e33a5.png)

**Comment by BitWuehler** [comment]
> Hi, my settings.yaml is used on v0.5.2, have you tried to hit the refresh/recreate lower right rounded arrow?
> ![image](https://user-images.githubusercontent.com/10362303/204541255-52c8a48d-059f-4187-b31f-2de7464e33a5.png)
> 

Wow. Thanks a lot. Doesn't thought it would be so easy 😅
Even restarted everything several times...

**Comment by Magelo** [comment]
Almost with every Homepage updates I have to use this rounded arrow to force a refresh/recreate Homepage layout. Glad it helped!

**Comment by BitWuehler** [comment]
After I red the commid, it's reasonable that, that it's still a bug and not a feature 😅

**Comment by shamoon** [comment]
If anyone here is able to test #963 I *think* it should mitigate this, at least in the most common situation

**Comment by afentoe** [comment]
I am experiencing initial display issues when container is created.
Should this be fixed in 0.7.6 with this merge: https://github.com/benphelps/homepage/pull/609
where this current bug was mentioned, or should I try https://github.com/benphelps/homepage/pull/963
as well to check for fixes with the initial loading as well?

My issue:
Using setting.yaml with rows:
```
layout:
  Proxmox:
    style: row
    columns: 7
```
Will display as rows on initial container launch.

A forced file save of settings.yaml, will trigger the correct layout.

Or do you want me to create a new bug for this?

**Comment by shamoon** [comment]
What you're describing is this bug, so no need for a new one. #609 didn't work unfortunately, #963 is a second attempt. Unfortunately testing #963 isn't trivial as it requires building the docker image but I think we can get it merged into `main` (unless any issues come up) and folks can test it there.

**Comment by shamoon** [comment]
If anyone is interested in testing the `main` image, I think I've finally got this one licked (totally).
