### ISSUE TITLE
[Bug] Error compiling from source

### ISSUE THREAD

**Issue by nomadtechiemike** [benphelps/homepage#590]
### Description

Fresh install using turnkey nodejs

failed to build 

root@Homepage /opt/homepage# npm run build

> startpage@0.1.0 build
> next build

Failed to compile.

./src/components/quicklaunch.jsx
110:89  Error: Missing "key" prop for element in iterator  react/jsx-key

./src/components/widgets/datetime/datetime.jsx
18:9  Warning: The 'dateFormat' object construction makes the dependencies of useEffect Hook (at line 26) change on every render. Move it inside the useEffect callback. Alternatively, wrap the initialization of 'dateFormat' in its own useMemo() Hook.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types .root@Homepage /opt/homepage# 

### Steps to reproduce

create container on proxmox

use turnkey nodejs template

start container run updates 

clone repo run npm install and npm run build 

### homepage version

0.5.2

### Installation method

Source

**Comment by shamoon** [comment]
Something aint right here, since the project does build e.g. https://github.com/benphelps/homepage/actions/runs/3579199822
Also that error seems old, e.g. https://github.com/benphelps/homepage/blob/94678be85e1c3e0396c665d6fa667e6e947ca560/src/components/quicklaunch.jsx#L131
The warning was closed by #570 https://github.com/benphelps/homepage/commit/44c2a1ecbd1304f1b37c9e0e41c08b16df76eacc

Can you double-check youre using the latest version of the codebase?

**Comment by vladaurosh** [comment]
I am getting the exact same error:
```
./src/components/quicklaunch.jsx
110:89  Error: Missing "key" prop for element in iterator
```

Using latest code from https://github.com/benphelps/homepage/archive/refs/tags/v0.5.3.tar.gz

Is this error pointing to line 110 not 131?

**Comment by JazzFisch** [comment]
Per the README.md, this project is meant to be built and used via pnpm.

https://github.com/benphelps/homepage#development

**Comment by vladaurosh** [comment]
It says this as well:
`Then install dependencies and build the production bundle (I'm using pnpm here, **you can use npm or yarn if you like**):`

**Comment by shamoon** [comment]
Ah thanks for pointing out line 110. I’m still unclear why I don’t see this but I’ll dig into it later

**Comment by shamoon** [comment]
Yea, cant repro. What version of node are folks using?

It doesnt really make sense because if you run the lint e.g. `pnpm lint` it doesnt have an issue with that line (but does if you dont have a `key` on 131), looking at it I dont think it really needs a key there either.

Anyway, can you guys test the branch https://github.com/benphelps/homepage/tree/fix-590 and see if that makes a difference?

**Comment by vladaurosh** [comment]
I am on node 14.20.0. 
I work around this by adding 
` "react/jsx-key": "off"`
into .eslintrc.json .

I'll try with this branch, and report results.

**Comment by vladaurosh** [comment]
Hello @shamoon 
fix-590 indeed makes a difference, no "Missing key" error for me this time. :)

**Comment by shamoon** [comment]
> fix-590 indeed makes a difference, no "Missing key" error for me this time. :)

Awesome thanks
