### ISSUE TITLE
[Feature Request] Site up or down indicator

### ISSUE THREAD

**Issue by richardphi1618** [benphelps/homepage#78]
Similar to what uptime kuma would do it would be nice to use the green light you use for container status to indicate if a website is up or down (404 / 502 / 300 / etc). I use uptime kuma as the example but it doesn't need to be that sophisticated a simple yes/no of if a site is up or down would be helpful.

**Comment by benphelps** [comment]
Something similar to the docker status icons like shown here https://github.com/benphelps/homepage/wiki/Services#docker-integration ?

**Comment by richardphi1618** [comment]
Yea this is great for at a glance now the status of my docker environment (love this). I fight with cloudflare some days and have some apps I show through a domain name / off site apps too. I don't take for granted just because the container is working that the site is reachable / functioning you know?

**Comment by rolikeusch** [comment]
I would also like to see this feature. I use [wirestat](https://github.com/ssddanbrown/wirestat) to monitor my servers and if something fails It gives the status 500. so it would be great to have this in homepage.

perhaps it would also possible to have more stats in  [wirestat](https://github.com/ssddanbrown/wirestat) in homepage, like cpu or ram usage 😉

**Comment by DanJackiels** [comment]
> Something similar to the docker status icons like shown here https://github.com/benphelps/homepage/wiki/Services#docker-integration ?

It would be awesome if this would behave the same way for both docker and non-docker services to keep it consistent.
Because right now non-docker apps don't have an indicator light.

And also, since I can't hide their widget they stick out when in a group with docker containers.

Otherwise, I love this dashboard. Thanks for making it! :)

![image](https://user-images.githubusercontent.com/47887738/191391060-4a344c3f-79d1-4124-afb2-cb6ab00fb3d8.png)

**Comment by JazzFisch** [comment]
This could potentially be difficult to do.  On one hand, you could define a URL (http://container_name:port) but that only works if you are the same docker network, but wouldn't let you know if there was an issue with your reverse proxy.  On the other hand, Docker doesn't allow containers to send network traffic to anything on their public IP.  So if you configured homepage with https://app.mydomain.tld:port and that resolves to the same IP that homepage is on, it would always show down.

**Comment by shamoon** [comment]
I was thinking about this and I agree JazzFirsch, the issues you noted above may be problematic for users but I guess the question is how much the software has to protect users against 'mistakes', e.g. is it enough to put a warning like this in the docs? 

I made an implementation of this (screenshot) which uses the proxy backend, that way you could theoretically setup a ping to the local IP/host to test up / down even if the public URL/ip wouldn't work e.g. because of a reverse proxy.

Curious about people's thoughts.

<img width="496" alt="Screen Shot 2022-10-12 at 2 25 40 PM" src="https://user-images.githubusercontent.com/4887959/195716424-d07ecf61-3b94-403d-a057-7f32f8447c37.png">
